uploads = []
generated = []

[[outputs]]
id = "n1IuSNCqy6BlweDbOAuFT"
uri = "file://us-web-and-design.tar.gz"
type = "unspecified"
title = "US Web and Design — GitHub Upload Package"

[[outputs]]
id = "jbGM7NsKIKcIaEUi6qy1H"
uri = "file://github-upload.tar.gz"
type = "unspecified"
title = "GitHub Upload Package (38MB — source code only)"
